// <auto-generated />
namespace Infraestructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class v4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v4));
        
        string IMigrationMetadata.Id
        {
            get { return "201911112234298_v4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
